ERROR|23/Feb/2021 15:08:20|exception|3441|140162106877696|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|23/Feb/2021 15:08:20|basehttp|3441|140162106877696|"GET /manager/html HTTP/1.1" 500 59
ERROR|23/Feb/2021 16:20:45|exception|6288|140527563433728|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|23/Feb/2021 16:20:45|basehttp|6288|140527563433728|"GET /manager/html HTTP/1.1" 500 59
ERROR|23/Feb/2021 16:22:17|log|6288|140527563433728|Internal Server Error: /access_token/
Traceback (most recent call last):
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/www/html/mobilitysqr_staging/mobility_apps/employee/views.py", line 1918, in post
    otp=User.objects.filter(otp=otp).values("id")
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/db/models/query.py", line 841, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/db/models/query.py", line 859, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1263, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1287, in _add_q
    split_subq=split_subq,
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1225, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1096, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/db/models/lookups.py", line 20, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/db/models/lookups.py", line 70, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 1807, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'fdfgd'
ERROR|23/Feb/2021 16:22:17|basehttp|6288|140527563433728|"POST /access_token/ HTTP/1.1" 500 18758
ERROR|23/Feb/2021 18:12:12|log|10908|140368832386816|Internal Server Error: /get_add/travel_request/
Traceback (most recent call last):
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/www/html/mobilitysqr_staging/mobility_apps/travel/views.py", line 122, in get
    for data in travel_request:
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/template/response.py", line 120, in __iter__
    'The response content must be rendered before it can be iterated over.'
django.template.response.ContentNotRenderedError: The response content must be rendered before it can be iterated over.
ERROR|23/Feb/2021 18:12:12|basehttp|10908|140368832386816|"GET /get_add/travel_request/?travel_req_status=2&org_id=ORG150866&emp_email=tushaar001 HTTP/1.1" 500 17807
ERROR|23/Feb/2021 18:12:16|log|10908|140368832386816|Internal Server Error: /get_add/travel_request/
Traceback (most recent call last):
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/www/html/mobilitysqr_staging/mobility_apps/travel/views.py", line 122, in get
    for data in travel_request:
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/template/response.py", line 120, in __iter__
    'The response content must be rendered before it can be iterated over.'
django.template.response.ContentNotRenderedError: The response content must be rendered before it can be iterated over.
ERROR|23/Feb/2021 18:12:16|basehttp|10908|140368832386816|"GET /get_add/travel_request/?travel_req_status=2&org_id=ORG150866&emp_email=tushaar001 HTTP/1.1" 500 17807
ERROR|23/Feb/2021 18:12:40|log|10908|140368725145344|Internal Server Error: /get_add/travel_request/
Traceback (most recent call last):
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/www/html/mobilitysqr_staging/mobility_apps/travel/views.py", line 122, in get
    for data in travel_request:
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/template/response.py", line 120, in __iter__
    'The response content must be rendered before it can be iterated over.'
django.template.response.ContentNotRenderedError: The response content must be rendered before it can be iterated over.
ERROR|23/Feb/2021 18:12:40|basehttp|10908|140368725145344|"GET /get_add/travel_request/?travel_req_status=2&org_id=ORG150866&emp_email=tushaar001 HTTP/1.1" 500 17807
ERROR|23/Feb/2021 18:12:55|log|10908|140368841828096|Internal Server Error: /get_add/travel_request/
Traceback (most recent call last):
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/www/html/mobilitysqr_staging/mobility_apps/travel/views.py", line 122, in get
    for data in travel_request:
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/template/response.py", line 120, in __iter__
    'The response content must be rendered before it can be iterated over.'
django.template.response.ContentNotRenderedError: The response content must be rendered before it can be iterated over.
ERROR|23/Feb/2021 18:12:55|basehttp|10908|140368841828096|"GET /get_add/travel_request/?travel_req_status=2&org_id=ORG150866&emp_email=tushaar001 HTTP/1.1" 500 17807
ERROR|23/Feb/2021 18:17:16|log|10908|140368841828096|Internal Server Error: /get_add/travel_request/
Traceback (most recent call last):
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/www/html/mobilitysqr_staging/mobility_apps/travel/views.py", line 122, in get
    for data in travel_request:
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/template/response.py", line 120, in __iter__
    'The response content must be rendered before it can be iterated over.'
django.template.response.ContentNotRenderedError: The response content must be rendered before it can be iterated over.
ERROR|23/Feb/2021 18:17:16|basehttp|10908|140368841828096|"GET /get_add/travel_request/?travel_req_status=2&org_id=ORG150866&emp_email=div944 HTTP/1.1" 500 17761
ERROR|23/Feb/2021 18:17:47|log|10908|140368841828096|Internal Server Error: /get_add/travel_request/
Traceback (most recent call last):
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/www/html/mobilitysqr_staging/mobility_apps/travel/views.py", line 122, in get
    for data in travel_request:
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/template/response.py", line 120, in __iter__
    'The response content must be rendered before it can be iterated over.'
django.template.response.ContentNotRenderedError: The response content must be rendered before it can be iterated over.
ERROR|23/Feb/2021 18:17:47|basehttp|10908|140368841828096|"GET /get_add/travel_request/?travel_req_status=2&org_id=ORG150866&emp_email=div944 HTTP/1.1" 500 17762
ERROR|23/Feb/2021 18:18:00|log|10908|140368832386816|Internal Server Error: /get_add/travel_request/
Traceback (most recent call last):
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/www/html/mobilitysqr_staging/mobility_apps/travel/views.py", line 122, in get
    for data in travel_request:
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/template/response.py", line 120, in __iter__
    'The response content must be rendered before it can be iterated over.'
django.template.response.ContentNotRenderedError: The response content must be rendered before it can be iterated over.
ERROR|23/Feb/2021 18:18:00|basehttp|10908|140368832386816|"GET /get_add/travel_request/?travel_req_status=2&org_id=ORG150866&emp_email=div944 HTTP/1.1" 500 17792
ERROR|23/Feb/2021 18:18:21|log|10908|140368832386816|Internal Server Error: /get_add/travel_request/
Traceback (most recent call last):
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/www/html/mobilitysqr_staging/mobility_apps/travel/views.py", line 122, in get
    for data in travel_request:
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/template/response.py", line 120, in __iter__
    'The response content must be rendered before it can be iterated over.'
django.template.response.ContentNotRenderedError: The response content must be rendered before it can be iterated over.
ERROR|23/Feb/2021 18:18:21|basehttp|10908|140368832386816|"GET /get_add/travel_request/?travel_req_status=2&org_id=ORG150866&emp_email=gauravg HTTP/1.1" 500 17793
ERROR|23/Feb/2021 18:20:12|log|10908|140368841828096|Internal Server Error: /get_add/travel_request/
Traceback (most recent call last):
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/www/html/mobilitysqr_staging/mobility_apps/travel/views.py", line 122, in get
    for data in travel_request:
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/template/response.py", line 120, in __iter__
    'The response content must be rendered before it can be iterated over.'
django.template.response.ContentNotRenderedError: The response content must be rendered before it can be iterated over.
ERROR|23/Feb/2021 18:20:12|basehttp|10908|140368841828096|"GET /get_add/travel_request/?travel_req_status=2&org_id=ORG150866&emp_email=gauravg HTTP/1.1" 500 17582
ERROR|23/Feb/2021 18:21:44|exception|10908|140368725145344|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|23/Feb/2021 18:21:44|basehttp|10908|140368725145344|"GET /manager/html HTTP/1.1" 500 59
ERROR|23/Feb/2021 18:29:48|log|10908|140368800663296|Internal Server Error: /get_add/travel_request/
Traceback (most recent call last):
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/www/html/mobilitysqr_staging/mobility_apps/travel/views.py", line 122, in get
    for data in travel_request:
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/template/response.py", line 120, in __iter__
    'The response content must be rendered before it can be iterated over.'
django.template.response.ContentNotRenderedError: The response content must be rendered before it can be iterated over.
ERROR|23/Feb/2021 18:29:48|basehttp|10908|140368800663296|"GET /get_add/travel_request/?travel_req_status=2&org_id=ORG150866&emp_email=tushaar001 HTTP/1.1" 500 17807
ERROR|23/Feb/2021 18:32:18|log|10908|140368800663296|Internal Server Error: /get_add/travel_request/
Traceback (most recent call last):
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/www/html/mobilitysqr_staging/mobility_apps/travel/views.py", line 122, in get
    for data in travel_request:
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/template/response.py", line 120, in __iter__
    'The response content must be rendered before it can be iterated over.'
django.template.response.ContentNotRenderedError: The response content must be rendered before it can be iterated over.
ERROR|23/Feb/2021 18:32:18|basehttp|10908|140368800663296|"GET /get_add/travel_request/?travel_req_status=2&org_id=ORG150866&emp_email=tushaar001 HTTP/1.1" 500 17807
ERROR|23/Feb/2021 18:45:29|log|10908|140368699967232|Internal Server Error: /get_add/travel_request/
Traceback (most recent call last):
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/www/html/mobilitysqr_staging/mobility_apps/travel/views.py", line 122, in get
    for data in travel_request:
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/template/response.py", line 120, in __iter__
    'The response content must be rendered before it can be iterated over.'
django.template.response.ContentNotRenderedError: The response content must be rendered before it can be iterated over.
ERROR|23/Feb/2021 18:45:29|basehttp|10908|140368699967232|"GET /get_add/travel_request/?travel_req_status=2&org_id=ORG150866&emp_email=tushaar001 HTTP/1.1" 500 17807
ERROR|23/Feb/2021 18:50:13|log|10908|140368699967232|Internal Server Error: /get_add/travel_request/
Traceback (most recent call last):
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/www/html/mobilitysqr_staging/mobility_apps/travel/views.py", line 122, in get
    for data in travel_request:
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/template/response.py", line 120, in __iter__
    'The response content must be rendered before it can be iterated over.'
django.template.response.ContentNotRenderedError: The response content must be rendered before it can be iterated over.
ERROR|23/Feb/2021 18:50:13|basehttp|10908|140368699967232|"GET /get_add/travel_request/?travel_req_status=2&org_id=ORG150866&emp_email=tushaar001 HTTP/1.1" 500 17807
ERROR|23/Feb/2021 18:50:23|log|10908|140368708359936|Internal Server Error: /get_add/travel_request/
Traceback (most recent call last):
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/www/html/mobilitysqr_staging/mobility_apps/travel/views.py", line 122, in get
    for data in travel_request:
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/template/response.py", line 120, in __iter__
    'The response content must be rendered before it can be iterated over.'
django.template.response.ContentNotRenderedError: The response content must be rendered before it can be iterated over.
ERROR|23/Feb/2021 18:50:23|basehttp|10908|140368708359936|"GET /get_add/travel_request/?travel_req_status=2&org_id=ORG150866&emp_email=tushaar001 HTTP/1.1" 500 17807
ERROR|23/Feb/2021 18:50:27|log|10908|140368708359936|Internal Server Error: /get_add/travel_request/
Traceback (most recent call last):
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/www/html/mobilitysqr_staging/mobility_apps/travel/views.py", line 122, in get
    for data in travel_request:
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/template/response.py", line 120, in __iter__
    'The response content must be rendered before it can be iterated over.'
django.template.response.ContentNotRenderedError: The response content must be rendered before it can be iterated over.
ERROR|23/Feb/2021 18:50:27|basehttp|10908|140368708359936|"GET /get_add/travel_request/?travel_req_status=2&org_id=ORG150866&emp_email=tushaar001 HTTP/1.1" 500 17807
ERROR|23/Feb/2021 18:51:10|log|10908|140368708359936|Internal Server Error: /get_add/travel_request/
Traceback (most recent call last):
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/www/html/mobilitysqr_staging/mobility_apps/travel/views.py", line 122, in get
    for data in travel_request:
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/template/response.py", line 120, in __iter__
    'The response content must be rendered before it can be iterated over.'
django.template.response.ContentNotRenderedError: The response content must be rendered before it can be iterated over.
ERROR|23/Feb/2021 18:51:10|basehttp|10908|140368708359936|"GET /get_add/travel_request/?travel_req_status=2&org_id=ORG150866&emp_email=tushaar001 HTTP/1.1" 500 17807
ERROR|23/Feb/2021 18:52:11|log|10908|140368708359936|Internal Server Error: /get_add/travel_request/
Traceback (most recent call last):
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/www/html/mobilitysqr_staging/mobility_apps/travel/views.py", line 122, in get
    for data in travel_request:
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/template/response.py", line 120, in __iter__
    'The response content must be rendered before it can be iterated over.'
django.template.response.ContentNotRenderedError: The response content must be rendered before it can be iterated over.
ERROR|23/Feb/2021 18:52:11|basehttp|10908|140368708359936|"GET /get_add/travel_request/?travel_req_status=2&org_id=ORG150866&emp_email=tushaar001 HTTP/1.1" 500 17807
ERROR|23/Feb/2021 19:36:51|basehttp|13079|140144245860096|You're accessing the development server over HTTPS, but it only supports HTTP.

ERROR|23/Feb/2021 20:17:00|exception|13079|140144245860096|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|23/Feb/2021 20:20:29|exception|13079|140144245860096|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|23/Feb/2021 20:20:35|exception|13079|140144245860096|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|23/Feb/2021 20:26:36|exception|13079|140144245860096|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|23/Feb/2021 21:08:42|exception|13079|140144245860096|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|23/Feb/2021 21:18:34|exception|13079|140144245860096|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|23/Feb/2021 21:27:28|exception|13079|140144245860096|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|23/Feb/2021 21:53:19|exception|13079|140144245860096|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|23/Feb/2021 22:14:43|exception|13079|140144245860096|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|23/Feb/2021 22:28:57|exception|13079|140144215176960|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|23/Feb/2021 22:28:57|basehttp|13079|140144215176960|"GET /manager/html HTTP/1.1" 500 59
ERROR|23/Feb/2021 23:13:22|exception|13079|140144215176960|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|23/Feb/2021 23:58:43|exception|13079|140144215176960|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|23/Feb/2021 23:58:43|basehttp|13079|140144215176960|"GET /manager/html HTTP/1.1" 500 59
ERROR|24/Feb/2021 00:48:44|exception|13079|140144215176960|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|24/Feb/2021 00:56:51|exception|13079|140144215176960|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|24/Feb/2021 04:03:23|exception|13079|140144245860096|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|24/Feb/2021 04:53:38|exception|13079|140144245860096|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|24/Feb/2021 06:32:13|exception|13079|140144245860096|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|24/Feb/2021 06:35:08|exception|13079|140144245860096|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|24/Feb/2021 06:44:47|exception|13079|140144245860096|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|24/Feb/2021 08:08:38|exception|13079|140144245860096|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|24/Feb/2021 08:58:25|exception|13079|140144215176960|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|24/Feb/2021 09:16:44|exception|13079|140144215176960|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|24/Feb/2021 10:47:03|exception|13079|140144193410816|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|24/Feb/2021 10:55:21|log|13079|140143826556672|Internal Server Error: /get_travel_status_summary/
Traceback (most recent call last):
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/www/html/mobilitysqr_staging/mobility_apps/travel/views.py", line 960, in get
    travelserializersssts=Travel_Request_Action_History.objects.filter(travel_req_id_id=request.GET['travel_req_id'],email_id=travelserializerss[0]['supervisor'],approval_level="0").values(
  File "/home/mobilitysqr/.local/lib/python3.6/site-packages/django/db/models/query.py", line 303, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range
ERROR|24/Feb/2021 10:55:21|basehttp|13079|140143826556672|"GET /get_travel_status_summary/?travel_req_id=TR322248&org_id=ORG150866 HTTP/1.1" 500 17714
ERROR|24/Feb/2021 12:08:58|exception|13079|140143826556672|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|24/Feb/2021 12:14:10|exception|13079|140143818163968|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
ERROR|24/Feb/2021 13:01:38|exception|13079|140144193410816|Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
