ERROR|13/May/2021 13:59:15|log|24141|139993677780736|Internal Server Error: /getassignmentletter/
Traceback (most recent call last):
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/media/tspl26/D/raju_python/mobility_env/mobilitysqr_live/mobility_apps/letter/views.py", line 325, in get
    template = get_template(lettername)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: Long_Term_Assignment_ORG150866_vhHei4D.html
ERROR|13/May/2021 13:59:15|basehttp|24141|139993677780736|"GET /getassignmentletter/?travel_req_id=TR166926 HTTP/1.1" 500 20672
ERROR|13/May/2021 14:02:12|log|24141|139993677780736|Internal Server Error: /getassignmentletter/
Traceback (most recent call last):
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/media/tspl26/D/raju_python/mobility_env/mobilitysqr_live/mobility_apps/letter/views.py", line 344, in get
    templatess = get_template(letternamess)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: Visa_ORG150866_JGSxlBy.html
ERROR|13/May/2021 14:02:12|basehttp|24141|139993677780736|"GET /getassignmentletter/?travel_req_id=TR166926 HTTP/1.1" 500 20564
ERROR|13/May/2021 14:28:20|log|26340|139653890225920|Internal Server Error: /getassignmentletter/
Traceback (most recent call last):
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/media/tspl26/D/raju_python/mobility_env/mobilitysqr_live/mobility_apps/letter/views.py", line 346, in get
    templatess = get_template(letternamess)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: Visa_ORG150866_ONoMlUy.html
ERROR|13/May/2021 14:28:20|basehttp|26340|139653890225920|"GET /getassignmentletter/?travel_req_id=TR166926 HTTP/1.1" 500 20564
INFO|13/May/2021 14:58:11|basehttp|26340|139653890225920|"GET /get_view_travel_request/?travel_req_id=TR740800&org_id=ORG150866 HTTP/1.1" 200 3934
ERROR|13/May/2021 16:02:58|log|29616|140291326715648|Internal Server Error: /getassignmentletter/
Traceback (most recent call last):
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/media/tspl26/D/raju_python/mobility_env/mobilitysqr_live/mobility_apps/letter/views.py", line 327, in get
    template = get_template(lettername)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: Long_Term_Assignment_ORG150866_iXOwFfJ.html
ERROR|13/May/2021 16:02:58|basehttp|29616|140291326715648|"GET /getassignmentletter/?travel_req_id=TR166926 HTTP/1.1" 500 20672
WARNING|13/May/2021 16:25:03|log|30892|139753230296832|Unauthorized: /get_view_travel_request/
WARNING|13/May/2021 16:25:03|basehttp|30892|139753230296832|"GET /get_view_travel_request/?travel_req_id=TR740800&org_id=ORG150866 HTTP/1.1" 401 183
INFO|13/May/2021 16:25:07|basehttp|30892|139753230296832|"POST /api/custom/login/ HTTP/1.1" 200 455
INFO|13/May/2021 16:25:19|basehttp|30892|139753230296832|"GET /get_view_travel_request/?travel_req_id=TR740800&org_id=ORG150866 HTTP/1.1" 200 3934
ERROR|13/May/2021 16:51:00|log|31832|140443403220736|Internal Server Error: /get_view_travel_request/
Traceback (most recent call last):
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/media/tspl26/D/raju_python/mobility_env/mobilitysqr_live/mobility_apps/travel/views.py", line 637, in get
    Secondory_Assignment_ID = Secondory_Assignment.objects.filter(organization_id=request.GET['org_id'])
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/db/models/query.py", line 841, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/db/models/query.py", line 859, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/db/models/sql/query.py", line 1263, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/db/models/sql/query.py", line 1287, in _add_q
    split_subq=split_subq,
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/db/models/sql/query.py", line 1164, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/db/models/sql/query.py", line 1028, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/db/models/sql/query.py", line 1389, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'organization_id' into field. Choices are: Accommodation_Type, Actual_End_Date, Actual_Start_Date, Add_Assignment_Attachment, Assignment_Extended_to, Assignment_ID, Assignment_Type, Employee_ID, Entity_Type, Family_Size, Home_Country, Host_City, Host_Country, Host_State, Payroll_Type, Secondory_Assignment_ID, Tax_Equalization, Tentative_Assignment_End_Date, Tentative_Assignment_Start_Date, Ticket_ID, column1, column10, column11, column12, column2, column3, column4, column5, column6, column7, column8, column9, created_by, date_created, date_modified, home_compensation, host_compensation, id, modified_by, organization, status, visa_details
ERROR|13/May/2021 16:51:00|basehttp|31832|140443403220736|"GET /get_view_travel_request/?travel_req_id=TR740800&org_id=ORG150866 HTTP/1.1" 500 22487
ERROR|13/May/2021 16:55:49|log|31964|140166064895744|Internal Server Error: /get_view_travel_request/
Traceback (most recent call last):
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/media/tspl26/D/raju_python/mobility_env/mobilitysqr_live/mobility_apps/travel/views.py", line 638, in get
    assignment_type_id = Secondory_Assignment.objects.filter(organization_id=request.GET['org_id'])
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/db/models/query.py", line 841, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/db/models/query.py", line 859, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/db/models/sql/query.py", line 1263, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/db/models/sql/query.py", line 1287, in _add_q
    split_subq=split_subq,
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/db/models/sql/query.py", line 1164, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/db/models/sql/query.py", line 1028, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/db/models/sql/query.py", line 1389, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'organization_id' into field. Choices are: Accommodation_Type, Actual_End_Date, Actual_Start_Date, Add_Assignment_Attachment, Assignment_Extended_to, Assignment_ID, Assignment_Type, Employee_ID, Entity_Type, Family_Size, Home_Country, Host_City, Host_Country, Host_State, Payroll_Type, Secondory_Assignment_ID, Tax_Equalization, Tentative_Assignment_End_Date, Tentative_Assignment_Start_Date, Ticket_ID, column1, column10, column11, column12, column2, column3, column4, column5, column6, column7, column8, column9, created_by, date_created, date_modified, home_compensation, host_compensation, id, modified_by, organization, status, visa_details
ERROR|13/May/2021 16:55:49|basehttp|31964|140166064895744|"GET /get_view_travel_request/?travel_req_id=TR740800&org_id=ORG150866 HTTP/1.1" 500 22482
INFO|13/May/2021 16:56:41|basehttp|32051|140572957284096|"GET /get_view_travel_request/?travel_req_id=TR740800&org_id=ORG150866 HTTP/1.1" 200 27011
INFO|13/May/2021 17:07:03|basehttp|32362|140038621779712|"GET /get_view_travel_request/?travel_req_id=TR740800&org_id=ORG150866 HTTP/1.1" 200 25572
INFO|13/May/2021 17:08:02|basehttp|32428|139986820495104|"GET /get_view_travel_request/?travel_req_id=TR740800&org_id=ORG150866 HTTP/1.1" 200 27011
INFO|13/May/2021 17:08:21|basehttp|32428|139986820495104|"GET /get_view_travel_request/?travel_req_id=TR740800&org_id=ORG150866 HTTP/1.1" 200 27011
INFO|13/May/2021 17:08:41|basehttp|32463|139711286552320|"GET /get_view_travel_request/?travel_req_id=TR740800&org_id=ORG150866 HTTP/1.1" 200 25572
INFO|13/May/2021 17:15:20|basehttp|32767|139892939888384|"GET /get_view_travel_request/?travel_req_id=TR740800&org_id=ORG150866 HTTP/1.1" 200 9725
WARNING|13/May/2021 18:35:44|log|2702|139915706054400|Unauthorized: /get_create_assignment/
WARNING|13/May/2021 18:35:44|basehttp|2702|139915706054400|"GET /get_create_assignment/?travel_req_id=TR740800&org_id=ORG150866 HTTP/1.1" 401 183
INFO|13/May/2021 18:35:49|basehttp|2702|139915706054400|"POST /api/custom/login/ HTTP/1.1" 200 455
ERROR|13/May/2021 18:36:09|log|2702|139915706054400|Internal Server Error: /get_create_assignment/
Traceback (most recent call last):
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/utils/datastructures.py", line 77, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'home'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/media/tspl26/D/raju_python/mobility_env/mobilitysqr_live/mobility_apps/master/views/assignment_type.py", line 153, in get
    if request.GET['home']:
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/utils/datastructures.py", line 79, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'home'
ERROR|13/May/2021 18:36:09|basehttp|2702|139915706054400|"GET /get_create_assignment/?travel_req_id=TR740800&org_id=ORG150866 HTTP/1.1" 500 19972
ERROR|13/May/2021 18:37:10|log|2975|139860815472384|Internal Server Error: /get_create_assignment/
Traceback (most recent call last):
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/utils/datastructures.py", line 77, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'Ticket_ID'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/media/tspl26/D/raju_python/mobility_env/mobilitysqr_live/mobility_apps/master/views/assignment_type.py", line 156, in get
    assignment_type=Create_Assignment.objects.filter(Ticket_ID=request.GET['Ticket_ID'],organization=request.GET['org_id'])
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/utils/datastructures.py", line 79, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'Ticket_ID'
ERROR|13/May/2021 18:37:10|basehttp|2975|139860815472384|"GET /get_create_assignment/?travel_req_id=TR740800&org_id=ORG150866&home= HTTP/1.1" 500 20108
INFO|13/May/2021 18:37:23|basehttp|2975|139860815472384|"GET /get_create_assignment/?Ticket_ID=TR740800&org_id=ORG150866&home= HTTP/1.1" 200 1205
INFO|13/May/2021 18:53:53|basehttp|2975|139860815472384|"GET /get_view_travel_request/?travel_req_id=TR740800&org_id=ORG150866 HTTP/1.1" 200 3934
ERROR|13/May/2021 18:57:52|log|3762|140013699499776|Internal Server Error: /get_view_travel_request/
Traceback (most recent call last):
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/media/tspl26/D/raju_python/mobility_env/mobilitysqr_live/mobility_apps/travel/views.py", line 640, in get
    if assignment_type_serializer.data:
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super(ListSerializer, self).data
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/rest_framework/serializers.py", line 262, in data
    self._data = self.to_representation(self.instance)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/rest_framework/serializers.py", line 686, in to_representation
    self.child.to_representation(item) for item in iterable
TypeError: 'Secondory_Assignment' object is not iterable
ERROR|13/May/2021 18:57:52|basehttp|3762|140013699499776|"GET /get_view_travel_request/?travel_req_id=TR740800&org_id=ORG150866 HTTP/1.1" 500 19917
ERROR|13/May/2021 18:58:19|log|3851|140501294225152|Internal Server Error: /get_view_travel_request/
Traceback (most recent call last):
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/media/tspl26/D/raju_python/mobility_env/mobilitysqr_live/mobility_apps/travel/views.py", line 640, in get
    if assignment_type_serializer.data:
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super(ListSerializer, self).data
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/rest_framework/serializers.py", line 262, in data
    self._data = self.to_representation(self.instance)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/rest_framework/serializers.py", line 686, in to_representation
    self.child.to_representation(item) for item in iterable
TypeError: 'Secondory_Assignment' object is not iterable
ERROR|13/May/2021 18:58:19|basehttp|3851|140501294225152|"GET /get_view_travel_request/?travel_req_id=TR740800&org_id=ORG150866 HTTP/1.1" 500 19917
INFO|13/May/2021 18:59:09|basehttp|3894|139760332773120|"GET /get_view_travel_request/?travel_req_id=TR740800&org_id=ORG150866 HTTP/1.1" 200 5103
INFO|13/May/2021 19:02:13|basehttp|3989|139951692220160|"GET /get_view_travel_request/?travel_req_id=TR740800&org_id=ORG150866 HTTP/1.1" 200 5135
ERROR|13/May/2021 19:41:01|log|5641|140216131401472|Internal Server Error: /getassignmentletter/
Traceback (most recent call last):
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/media/tspl26/D/raju_python/mobility_env/mobilitysqr_live/mobility_apps/letter/views.py", line 328, in get
    template = get_template(lettername)
  File "/media/tspl26/D/raju_python/mobility_env/lib/python3.7/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: Long_Term_Assignment_ORG150866_iXOwFfJ.html
ERROR|13/May/2021 19:41:01|basehttp|5641|140216131401472|"GET /getassignmentletter/?travel_req_id=TR166926 HTTP/1.1" 500 20672
